#!/usr/bin/env python3

import argparse
from pathlib import Path

from lib import dem_tools, osm_tools, tile_tools
from lib import constants
from lib.create_buffer import create_buffer

parser = argparse.ArgumentParser("tiles-from-reference")
parser.add_argument(
        "reference_geometry", 
        help="A gpx or geojson feature collection to use a reference for the map bounds", 
        type=Path
    )

parser.add_argument(
        "output_dir",
        type=Path,
        help="Output directory"
    )

parser.add_argument(
        "--trail_id",
        type=int,
        default=None,
        help="OSM Relation ID of the map's main trail. Default: None"
    )

parser.add_argument(
        "--buffer_radius",
        type=int,
        default=6000,
        help="Radius (in meters) of the buffer around the reference geometry. Default: 6000"
    )
args = parser.parse_args()
# print(args.reference_geometry)
refernce_path = Path(args.reference_geometry).absolute()
output_dir = Path(args.output_dir).absolute()
print(f"{constants.YELLOW}Creating buffer polygon...{constants.RESET}")
buffer, bbox = create_buffer(str(refernce_path), args.buffer_radius)
dem_tools.main(output_dir, bbox, buffer)
osm_tools.main(output_dir, buffer, args.trail_id)
tile_tools.main(output_dir)


