namespace BackcountryMapGraph;

table Node {
  id:uint;
  x:double;
  y:double;
}

table Point {
  x:double;
  y:double;
  z:double;
}

table GeometryMeta {
  points:[Point];
  seg_lengths:[double];
  cumulative_lengths:[double];
  total_length:double;
}

table Edge {
  start_node_id:uint;
  end_node_id:uint;
  weight:double;
  
  // REMOVED: geometry_wkb:[ubyte];
  
  geometry_meta:GeometryMeta;  // Contains all the points needed
  
  bbox_min_x:double;
  bbox_min_y:double;
  bbox_max_x:double;
  bbox_max_y:double;
}

table Graph {
  nodes:[Node];
  edges:[Edge];
}

root_type Graph;