# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BackcountryMapGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CumulativeMeasure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CumulativeMeasure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCumulativeMeasure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CumulativeMeasure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CumulativeMeasure
    def CumulativeDistance(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CumulativeMeasure
    def CumulativeGain(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # CumulativeMeasure
    def CumulativeLoss(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def CumulativeMeasureStart(builder):
    builder.StartObject(3)

def Start(builder):
    CumulativeMeasureStart(builder)

def CumulativeMeasureAddCumulativeDistance(builder, cumulativeDistance):
    builder.PrependFloat64Slot(0, cumulativeDistance, 0.0)

def AddCumulativeDistance(builder, cumulativeDistance):
    CumulativeMeasureAddCumulativeDistance(builder, cumulativeDistance)

def CumulativeMeasureAddCumulativeGain(builder, cumulativeGain):
    builder.PrependFloat64Slot(1, cumulativeGain, 0.0)

def AddCumulativeGain(builder, cumulativeGain):
    CumulativeMeasureAddCumulativeGain(builder, cumulativeGain)

def CumulativeMeasureAddCumulativeLoss(builder, cumulativeLoss):
    builder.PrependFloat64Slot(2, cumulativeLoss, 0.0)

def AddCumulativeLoss(builder, cumulativeLoss):
    CumulativeMeasureAddCumulativeLoss(builder, cumulativeLoss)

def CumulativeMeasureEnd(builder):
    return builder.EndObject()

def End(builder):
    return CumulativeMeasureEnd(builder)
