# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BackcountryMapGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Edge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Edge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Edge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Edge
    def StartNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Edge
    def EndNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Edge
    def Weight(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Edge
    def GeometryWkb(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Edge
    def GeometryWkbAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Edge
    def GeometryWkbLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Edge
    def GeometryWkbIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Edge
    def MeasuresForward(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from BackcountryMapGraph.CumulativeMeasure import CumulativeMeasure
            obj = CumulativeMeasure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Edge
    def MeasuresForwardLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Edge
    def MeasuresForwardIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Edge
    def MeasuresReverse(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from BackcountryMapGraph.CumulativeMeasure import CumulativeMeasure
            obj = CumulativeMeasure()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Edge
    def MeasuresReverseLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Edge
    def MeasuresReverseIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def EdgeStart(builder):
    builder.StartObject(6)

def Start(builder):
    EdgeStart(builder)

def EdgeAddStartNodeId(builder, startNodeId):
    builder.PrependUint32Slot(0, startNodeId, 0)

def AddStartNodeId(builder, startNodeId):
    EdgeAddStartNodeId(builder, startNodeId)

def EdgeAddEndNodeId(builder, endNodeId):
    builder.PrependUint32Slot(1, endNodeId, 0)

def AddEndNodeId(builder, endNodeId):
    EdgeAddEndNodeId(builder, endNodeId)

def EdgeAddWeight(builder, weight):
    builder.PrependFloat64Slot(2, weight, 0.0)

def AddWeight(builder, weight):
    EdgeAddWeight(builder, weight)

def EdgeAddGeometryWkb(builder, geometryWkb):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(geometryWkb), 0)

def AddGeometryWkb(builder, geometryWkb):
    EdgeAddGeometryWkb(builder, geometryWkb)

def EdgeStartGeometryWkbVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartGeometryWkbVector(builder, numElems):
    return EdgeStartGeometryWkbVector(builder, numElems)

def EdgeAddMeasuresForward(builder, measuresForward):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(measuresForward), 0)

def AddMeasuresForward(builder, measuresForward):
    EdgeAddMeasuresForward(builder, measuresForward)

def EdgeStartMeasuresForwardVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeasuresForwardVector(builder, numElems):
    return EdgeStartMeasuresForwardVector(builder, numElems)

def EdgeAddMeasuresReverse(builder, measuresReverse):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(measuresReverse), 0)

def AddMeasuresReverse(builder, measuresReverse):
    EdgeAddMeasuresReverse(builder, measuresReverse)

def EdgeStartMeasuresReverseVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMeasuresReverseVector(builder, numElems):
    return EdgeStartMeasuresReverseVector(builder, numElems)

def EdgeEnd(builder):
    return builder.EndObject()

def End(builder):
    return EdgeEnd(builder)
