# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BackcountryMapGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GeometryMeta(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GeometryMeta()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGeometryMeta(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GeometryMeta
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GeometryMeta
    def Points(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from BackcountryMapGraph.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GeometryMeta
    def PointsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GeometryMeta
    def PointsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # GeometryMeta
    def SegLengths(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # GeometryMeta
    def SegLengthsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # GeometryMeta
    def SegLengthsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GeometryMeta
    def SegLengthsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # GeometryMeta
    def CumulativeLengths(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # GeometryMeta
    def CumulativeLengthsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float64Flags, o)
        return 0

    # GeometryMeta
    def CumulativeLengthsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GeometryMeta
    def CumulativeLengthsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # GeometryMeta
    def TotalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def GeometryMetaStart(builder):
    builder.StartObject(4)

def Start(builder):
    GeometryMetaStart(builder)

def GeometryMetaAddPoints(builder, points):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder, points):
    GeometryMetaAddPoints(builder, points)

def GeometryMetaStartPointsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPointsVector(builder, numElems):
    return GeometryMetaStartPointsVector(builder, numElems)

def GeometryMetaAddSegLengths(builder, segLengths):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(segLengths), 0)

def AddSegLengths(builder, segLengths):
    GeometryMetaAddSegLengths(builder, segLengths)

def GeometryMetaStartSegLengthsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartSegLengthsVector(builder, numElems):
    return GeometryMetaStartSegLengthsVector(builder, numElems)

def GeometryMetaAddCumulativeLengths(builder, cumulativeLengths):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(cumulativeLengths), 0)

def AddCumulativeLengths(builder, cumulativeLengths):
    GeometryMetaAddCumulativeLengths(builder, cumulativeLengths)

def GeometryMetaStartCumulativeLengthsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartCumulativeLengthsVector(builder, numElems):
    return GeometryMetaStartCumulativeLengthsVector(builder, numElems)

def GeometryMetaAddTotalLength(builder, totalLength):
    builder.PrependFloat64Slot(3, totalLength, 0.0)

def AddTotalLength(builder, totalLength):
    GeometryMetaAddTotalLength(builder, totalLength)

def GeometryMetaEnd(builder):
    return builder.EndObject()

def End(builder):
    return GeometryMetaEnd(builder)
