# automatically generated by the FlatBuffers compiler, do not modify

# namespace: BackcountryMapGraph

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Node(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Node()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Node
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Node
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Node
    def X(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Node
    def Y(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # Node
    def Z(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def NodeStart(builder):
    builder.StartObject(4)

def Start(builder):
    NodeStart(builder)

def NodeAddId(builder, id):
    builder.PrependUint32Slot(0, id, 0)

def AddId(builder, id):
    NodeAddId(builder, id)

def NodeAddX(builder, x):
    builder.PrependFloat64Slot(1, x, 0.0)

def AddX(builder, x):
    NodeAddX(builder, x)

def NodeAddY(builder, y):
    builder.PrependFloat64Slot(2, y, 0.0)

def AddY(builder, y):
    NodeAddY(builder, y)

def NodeAddZ(builder, z):
    builder.PrependFloat64Slot(3, z, 0.0)

def AddZ(builder, z):
    NodeAddZ(builder, z)

def NodeEnd(builder):
    return builder.EndObject()

def End(builder):
    return NodeEnd(builder)
